# Numpy Tutorial

In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4,5]
print(lst)

[1, 2, 3, 4, 5]


In [6]:
a= np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [7]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [8]:
c = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print(c)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [11]:
type(c)

numpy.ndarray

In [13]:
print(a.size),
print(b.size),
print(c.size)

5
10
15


In [14]:
print(a.shape),
print(b.shape),
print(c.shape)

(5,)
(2, 5)
(1, 3, 5)


In [15]:
print(a.dtype),
print(b.dtype),
print(c.dtype)

int32
int32
int32


In [16]:
d = np.array([[[1,2,3.4,4,5],[6,7,8.2,9,10],[11,12,13.9,14,15]]])
print(c)
print(d.dtype)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]
float64


In [23]:
d.transpose()


array([[[ 1. ],
        [ 6. ],
        [11. ]],

       [[ 2. ],
        [ 7. ],
        [12. ]],

       [[ 3.4],
        [ 8.2],
        [13.9]],

       [[ 4. ],
        [ 9. ],
        [14. ]],

       [[ 5. ],
        [10. ],
        [15. ]]])

In [28]:
np.empty((4,4), dtype = int)

array([[4128860, 6029375, 3801155, 5570652],
       [6619251, 7536754, 7536732, 6619252],
       [6684774, 4259932, 7340144, 6357060],
       [6357108, 4980828, 6488175, 7077985]])

In [34]:
x= np.ones(6)
x

array([1., 1., 1., 1., 1., 1.])

In [35]:
y = np.ones((3,5))
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
z = np.ones((3,5), dtype=int)
z

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [37]:
x= np.zeros(6)
x

array([0., 0., 0., 0., 0., 0.])

In [39]:
y = np.zeros((3,5))
y

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
z = np.zeros((3,5), dtype=int)
z

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [42]:
a = np.zeros((3,5), dtype=str)
a

array([['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', '']], dtype='<U1')

In [43]:
b = np.zeros((3,5), dtype=bool)
b

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [44]:
b = np.ones((3,5), dtype=bool)
b

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [46]:
a = np.arange(1,20)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [51]:
a = np.arange(1,20,2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


In [52]:
a = np.arange(2,20,2)
print(a)

[ 2  4  6  8 10 12 14 16 18]


In [54]:
a = a.reshape((3,3))
print(a)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [55]:
b= np.arange(1,100,2)
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [56]:
b= b.reshape((10,5))
b

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [57]:
b= b.flatten()
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [58]:
a= a.ravel()
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])