# Numpy Tutorial

In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4,5]
print(lst)

[1, 2, 3, 4, 5]


In [6]:
a= np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [7]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [8]:
c = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print(c)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [11]:
type(c)

numpy.ndarray

In [13]:
print(a.size),
print(b.size),
print(c.size)

5
10
15


In [14]:
print(a.shape),
print(b.shape),
print(c.shape)

(5,)
(2, 5)
(1, 3, 5)


In [15]:
print(a.dtype),
print(b.dtype),
print(c.dtype)

int32
int32
int32


In [16]:
d = np.array([[[1,2,3.4,4,5],[6,7,8.2,9,10],[11,12,13.9,14,15]]])
print(c)
print(d.dtype)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]
float64


In [23]:
d.transpose()


array([[[ 1. ],
        [ 6. ],
        [11. ]],

       [[ 2. ],
        [ 7. ],
        [12. ]],

       [[ 3.4],
        [ 8.2],
        [13.9]],

       [[ 4. ],
        [ 9. ],
        [14. ]],

       [[ 5. ],
        [10. ],
        [15. ]]])